2022-03-26 11:48:23,543 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-26 11:49:14,115 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [26/Mar/2022 11:49:14] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-26 11:49:31,454 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [26/Mar/2022 11:49:31] "[31m[1mPOST /cc/workorder HTTP/1.1[0m" 401 -
2022-03-26 11:49:34,854 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [26/Mar/2022 11:49:34] "POST /cc/workorder HTTP/1.1" 200 -
2022-03-26 12:07:51,363 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-26 12:09:35,093 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [26/Mar/2022 12:09:35] "[31m[1mPOST /cc/workorder HTTP/1.1[0m" 401 -
2022-03-26 12:09:39,772 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [26/Mar/2022 12:09:39] "[31m[1mPOST /cc/workorder_add HTTP/1.1[0m" 401 -
2022-03-26 12:09:43,586 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [26/Mar/2022 12:09:43] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-26 12:09:54,345 ERROR main Thread-4 (process_request_thread) : Exception on /cc/workorder_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'cc_blueprint.workorder_add' did not return a valid response. The function either returned None or ended without a return statement.
2022-03-26 12:09:54,357 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [26/Mar/2022 12:09:54] "[35m[1mPOST /cc/workorder_add HTTP/1.1[0m" 500 -
2022-03-27 11:56:49,708 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-27 12:03:30,114 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:03:30] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-27 12:03:51,533 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:03:51] "[31m[1mPOST /cc/users HTTP/1.1[0m" 401 -
2022-03-27 12:04:06,654 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:04:06] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-27 12:04:23,685 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:04:23] "POST /cc/users HTTP/1.1" 200 -
2022-03-27 12:06:59,379 INFO werkzeug Thread-5 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:06:59] "[33mPOST /cc/workorder HTTP/1.1[0m" 404 -
2022-03-27 12:07:04,608 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:07:04] "[33mPOST /cc/workorder HTTP/1.1[0m" 404 -
2022-03-27 12:07:09,444 ERROR main Thread-7 (process_request_thread) : Exception on /cc/laporan [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 523, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Table 'cc_brimobdb.laporan' doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 163, in laporan
    cursor.execute(query, (start, limit,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 528, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'cc_brimobdb.laporan' doesn't exist
2022-03-27 12:07:09,561 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:07:09] "[35m[1mPOST /cc/laporan HTTP/1.1[0m" 500 -
2022-03-27 12:11:13,724 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-27 12:11:19,136 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 523, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Table 'cc_brimobdb.laporan' doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 163, in laporan
    cursor.execute(query, (start, limit,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 528, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'cc_brimobdb.laporan' doesn't exist
2022-03-27 12:11:19,143 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:11:19] "[35m[1mPOST /cc/laporan HTTP/1.1[0m" 500 -
2022-03-27 12:50:02,967 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:50:02] "[31m[1mPOST /cc/laporan HTTP/1.1[0m" 401 -
2022-03-27 12:50:23,850 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-27 12:50:24,039 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 523, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Column 'id' in field list is ambiguous

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 163, in laporan
    cursor.execute(query, (start, limit,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 528, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.IntegrityError: 1052 (23000): Column 'id' in field list is ambiguous
2022-03-27 12:50:24,042 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:50:24] "[35m[1mPOST /cc/laporan HTTP/1.1[0m" 500 -
2022-03-27 12:55:15,006 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-27 12:55:15,612 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [27/Mar/2022 12:55:15] "POST /cc/laporan HTTP/1.1" 200 -
2022-03-28 12:19:37,718 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 12:19:45,937 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:19:45] "[31m[1mPOST /cc/laporan_add HTTP/1.1[0m" 401 -
2022-03-28 12:19:52,294 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:19:52] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-28 12:20:06,740 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:20:06] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-28 12:20:32,332 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:20:32] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-28 12:21:27,581 INFO werkzeug Thread-5 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:21:27] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-28 12:21:47,420 ERROR main Thread-6 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 66, in __call__
    return self.params[index]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 154, in laporan_add
    cursor.execute(query, (no_laporan, user_id, lat_pelapor, long_pelapor, sub_kategori_id, laporan_text, status, tgl_submitted,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 263, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 68, in __call__
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2022-03-28 12:21:47,491 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:21:47] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 12:24:46,322 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 12:24:48,436 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:24:48] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-28 12:24:53,893 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:24:53] "POST /cc/login_user HTTP/1.1" 200 -
2022-03-28 12:35:02,055 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 12:35:12,955 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 66, in __call__
    return self.params[index]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 156, in laporan_add
    cursor.execute(query, (no_laporan, user_id, lat_pelapor, long_pelapor, sub_kategori_id, laporan_text, status,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 263, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 68, in __call__
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2022-03-28 12:35:12,964 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:35:12] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 12:36:43,309 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 12:36:46,708 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 66, in __call__
    return self.params[index]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 157, in laporan_add
    cursor.execute(query, (no_laporan, user_id, lat_pelapor, long_pelapor, sub_kategori_id, laporan_text, status,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 263, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 68, in __call__
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2022-03-28 12:36:46,712 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:36:46] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 12:37:33,394 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 12:38:46,711 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 66, in __call__
    return self.params[index]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 159, in laporan_add
    cursor.execute(query, (no_laporan, user_id, lat_pelapor, long_pelapor, sub_kategori_id, laporan_text, status,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 263, in execute
    stmt = RE_PY_PARAM.sub(psub, stmt)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 68, in __call__
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Not enough parameters for the SQL statement
2022-03-28 12:38:46,722 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:38:46] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 12:39:49,794 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 12:40:31,259 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 523, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`cc_brimobdb`.`laporan`, CONSTRAINT `fk_laporan_user_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`iduser`))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\renow\PycharmProjects\brimob-be\cc.py", line 159, in laporan_add
    cursor.execute(query, (no_laporan, user_id, lat_pelapor, long_pelapor, sub_kategori_id, laporan_text, status,))
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\mysql\connector\connection_cext.py", line 528, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`cc_brimobdb`.`laporan`, CONSTRAINT `fk_laporan_user_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`iduser`))
2022-03-28 12:40:31,282 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 12:40:31] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 18:01:42,320 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:01:45,195 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:01:45] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:02:38,005 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:02:43,843 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:02:43] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:05:26,835 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:05:28,921 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:05:28] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:06:12,558 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:06:12] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:07:01,961 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:07:03,675 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:07:03] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:08:52,248 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:08:57,050 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:08:57] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:21:43,109 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:21:53,037 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'cc_blueprint.laporan_add' did not return a valid response. The function either returned None or ended without a return statement.
2022-03-28 18:21:53,058 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:21:53] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 18:21:55,737 ERROR main Thread-2 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'cc_blueprint.laporan_add' did not return a valid response. The function either returned None or ended without a return statement.
2022-03-28 18:21:55,739 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:21:55] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 18:22:48,297 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:22:55,118 ERROR main Thread-1 (process_request_thread) : Exception on /cc/laporan_add [POST]
Traceback (most recent call last):
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "c:\users\renow\pycharmprojects\brimob-be\venv\lib\site-packages\flask\app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'cc_blueprint.laporan_add' did not return a valid response. The function either returned None or ended without a return statement.
2022-03-28 18:22:55,126 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:22:55] "[35m[1mPOST /cc/laporan_add HTTP/1.1[0m" 500 -
2022-03-28 18:26:13,402 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:26:30,829 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:26:39,573 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:26:39] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:28:22,392 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:28:27,366 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:28:27] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:30:17,349 INFO werkzeug MainThread :  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2022-03-28 18:30:26,512 INFO werkzeug Thread-1 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:30:26] "POST /cc/laporan_add HTTP/1.1" 200 -
2022-03-28 18:34:53,770 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [28/Mar/2022 18:34:53] "POST /cc/laporan HTTP/1.1" 200 -
